//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreUI.Tests.PizzaStoreDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaStoreDataService.IPizzaStoreDataService")]
    public interface IPizzaStoreDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetOrders", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetOrdersResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetOrders", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetOrdersResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethods", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethodsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[] GetPaymentMethods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethods", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethodsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[]> GetPaymentMethodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/PostNewOrder", ReplyAction="http://tempuri.org/IPizzaStoreDataService/PostNewOrderResponse")]
        bool PostNewOrder(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/PostNewOrder", ReplyAction="http://tempuri.org/IPizzaStoreDataService/PostNewOrderResponse")]
        System.Threading.Tasks.Task<bool> PostNewOrderAsync(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzas", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzasResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[] GetPizzas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzas", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzasResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[]> GetPizzasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[] GetPizzaSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[]> GetPizzaSizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCrustTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCrustTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[] GetCrustTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCrustTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCrustTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[]> GetCrustTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetSauceTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetSauceTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[] GetSauceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetSauceTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetSauceTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[]> GetSauceTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[] GetCheeseTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[]> GetCheeseTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppings", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[] GetToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppings", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[]> GetToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingCategories", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingCategoriesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[] GetToppingCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingCategories", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingCategoriesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[]> GetToppingCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacements", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacementsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[] GetToppingPlacements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacements", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacementsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[]> GetToppingPlacementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingLists", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingListsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[] GetToppingLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingLists", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingListsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[]> GetToppingListsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaStoreDataServiceChannel : PizzaStoreUI.Tests.PizzaStoreDataService.IPizzaStoreDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaStoreDataServiceClient : System.ServiceModel.ClientBase<PizzaStoreUI.Tests.PizzaStoreDataService.IPizzaStoreDataService>, PizzaStoreUI.Tests.PizzaStoreDataService.IPizzaStoreDataService {
        
        public PizzaStoreDataServiceClient() {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaStoreDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[] GetPaymentMethods() {
            return base.Channel.GetPaymentMethods();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[]> GetPaymentMethodsAsync() {
            return base.Channel.GetPaymentMethodsAsync();
        }
        
        public bool PostNewOrder(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder) {
            return base.Channel.PostNewOrder(newOrder);
        }
        
        public System.Threading.Tasks.Task<bool> PostNewOrderAsync(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder) {
            return base.Channel.PostNewOrderAsync(newOrder);
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[] GetPizzas() {
            return base.Channel.GetPizzas();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[]> GetPizzasAsync() {
            return base.Channel.GetPizzasAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[] GetPizzaSizes() {
            return base.Channel.GetPizzaSizes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[]> GetPizzaSizesAsync() {
            return base.Channel.GetPizzaSizesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[] GetCrustTypes() {
            return base.Channel.GetCrustTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[]> GetCrustTypesAsync() {
            return base.Channel.GetCrustTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[] GetSauceTypes() {
            return base.Channel.GetSauceTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[]> GetSauceTypesAsync() {
            return base.Channel.GetSauceTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[] GetCheeseTypes() {
            return base.Channel.GetCheeseTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[]> GetCheeseTypesAsync() {
            return base.Channel.GetCheeseTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[] GetToppings() {
            return base.Channel.GetToppings();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[]> GetToppingsAsync() {
            return base.Channel.GetToppingsAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[] GetToppingCategories() {
            return base.Channel.GetToppingCategories();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[]> GetToppingCategoriesAsync() {
            return base.Channel.GetToppingCategoriesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[] GetToppingPlacements() {
            return base.Channel.GetToppingPlacements();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[]> GetToppingPlacementsAsync() {
            return base.Channel.GetToppingPlacementsAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[] GetToppingLists() {
            return base.Channel.GetToppingLists();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[]> GetToppingListsAsync() {
            return base.Channel.GetToppingListsAsync();
        }
    }
}
